version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crmcrm
      POSTGRES_DB: shevark
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: python3 main.py
